version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
